#     â–ˆâ–ˆâ•—      â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•‘â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â–ˆâ–ˆâ–ˆâ–ˆâ•”â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•— â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘
#     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â•šâ•â• â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â•šâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘
#     â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•     â•šâ•â•â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•

## to get all emoji install "noto-fonts-emoji" or "yay -S noto-fonts-emoji"

# Don't print a new line at the start of the prompt
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[  âœ](bold #40f260)"  # The "success_symbol" is set to "âœ" with color "bold green"
error_symbol = "[  âœ](bold #f24054)"      # used if previous command failed

########### Dracula Color  ################
[aws]
style = "bold #f2f260"

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold #f240f2"

[git_commit]
commit_hash_length = 8
style = "bold #F2F280"


[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bold #f24054"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bold #f24054"
format = "$all_status$ahead_behind"
#===============================================================

# Use custom format
#format = """
#[|](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€::](bold green) """



# Indicates when in bash shell.
[custom.bash]
command = "echo ğŸ…± ğŸ…° ğŸ†‚ ğŸ…·"
when = '[ "$STARSHIP_SHELL" == "bash" ]'
style = "bold #f240f2"

# Indicates when in fish shell.
[custom.fish]
command = "echo : ğŸ…µ ğŸ…¸ ğŸ†‚ ğŸ…·"
when = 'test "$STARSHIP_SHELL" = "fish"'
style = "bold #f24054"

# Indicates when in zsh shell.
[custom.zsh]
command = "echo : ğŸ†‰ ğŸ†‚ ğŸ…·"
when = 'test "$STARSHIP_SHELL" = "zsh"'
style = "bold #30f0b2"

# Indicates when in Nushell.
[custom.nu]
command = "echo ğŸ¦€"
shell = 'bash'
when = '[ "$STARSHIP_SHELL" == "" ]' # not set in Nushell

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
format = "[ $hostname]($style)[î‚°](bg:#40f260 fg:#f24054)"
trim_at = "-"
style = "bold bg:#f24054 fg:#212128"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[time]
time_format = "%l:%M%P"
format = "$time($style)"
use_12hr = true
style = "bold bg:#f24054 fg:#666"
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"
style = "bold #f2f260"

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[ $path]($style)[ $read_only]($read_only_style)[î‚° ](#40f260)"
style = "bg:#40f260 fg:#212128"
read_only = "ğŸ”’"
read_only_style = "bg:#40f260 fg:#1a1a1e"

[username]
style_root = "bold bg:#f240f2 fg:212128"
format = "[ $user]($style)[î‚°](bg:#40f260 fg:#f24054)"
#format = "[$user]($style) on "
style_user = "bold bg:#f24054 fg:#212128"
disabled = false
show_always = true
